# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'egg-service-connection'
    subscriptionId: 'fe33316e-32fc-4647-b379-e35cbe12330f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-egg'
    location: 'North Central US'
    templateLocation: 'Linked artifact'
    csmFile: '.iac/main.bicep'
    deploymentMode: 'Incremental'