// <auto-generated />
using System;
using HemSoft.EggIncTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HemSoft.EggIncTracker.Data.Migrations
{
    [DbContext(typeof(EggIncContext))]
    [Migration("20240504000000_AddMissionsTable")]
    partial class AddMissionsTable
    {
        /// <summary>
        /// BuildTargetModel
        /// </summary>
        /// <param name="modelBuilder">Model builder</param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.ContractDto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("datetime2");

                b.Property<string>("EpicReward")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Identifier")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("StandardReward")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("Updated")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Identifier");

                b.HasIndex("Name");

                b.ToTable("Contracts");
            });

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.EventDto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime>("EndTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Identifier")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("StartTime")
                    .HasColumnType("datetime2");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<DateTime>("Updated")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("Identifier");

                b.HasIndex("Name");

                b.ToTable("Events");
            });

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.GoalDto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<int>("DailyPrestigeGoal")
                    .HasColumnType("int");

                b.Property<string>("PlayerName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("SEWeeklyGoal")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("Updated")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PlayerName");

                b.ToTable("Goals");
            });

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.MissionDto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("Capacity")
                    .HasColumnType("int");

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<int>("DurationSeconds")
                    .HasColumnType("int");

                b.Property<int>("DurationType")
                    .HasColumnType("int");

                b.Property<string>("FuelList")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsStandby")
                    .HasColumnType("bit");

                b.Property<DateTime>("LaunchTime")
                    .HasColumnType("datetime2");

                b.Property<int>("Level")
                    .HasColumnType("int");

                b.Property<int>("PlayerId")
                    .HasColumnType("int");

                b.Property<string>("PlayerName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<float>("QualityBump")
                    .HasColumnType("real");

                b.Property<DateTime>("ReturnTime")
                    .HasColumnType("datetime2");

                b.Property<float>("SecondsRemaining")
                    .HasColumnType("real");

                b.Property<int>("Ship")
                    .HasColumnType("int");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<int>("TargetArtifact")
                    .HasColumnType("int");

                b.Property<DateTime>("Updated")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("PlayerId");

                b.HasIndex("PlayerName");

                b.HasIndex("ReturnTime");

                b.HasIndex("Ship");

                b.HasIndex("Status");

                b.ToTable("Missions");
            });

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.PlayerDto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Created")
                    .HasColumnType("datetime2");

                b.Property<string>("EID")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PlayerName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Prestiges")
                    .HasColumnType("int");

                b.Property<string>("SEString")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("Updated")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("EID");

                b.HasIndex("PlayerName");

                b.ToTable("Players");
            });

            modelBuilder.Entity("HemSoft.EggIncTracker.Data.Dtos.MissionDto", b =>
            {
                b.HasOne("HemSoft.EggIncTracker.Data.Dtos.PlayerDto", "Player")
                    .WithMany()
                    .HasForeignKey("PlayerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Player");
            });
#pragma warning restore 612, 618
        }
    }
}
